# Generated by Django 4.2 on 2024-09-07 07:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="password_reset_otp",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
