# Generated by Django 4.2 on 2024-09-08 14:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_user_password_reset_otp"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="secondary_email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="Secondary email"
            ),
        ),
    ]
