# Generated by Django 4.2 on 2024-09-11 06:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_user_secondary_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="password_reset_otp_time",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
